import styles from 'styles/layout.module.scss'
import Head from 'next/head'
import { Header, Marquee, Desktop, Email, Footer } from 'components'
import { useSelector, getTrello, setCount, setHero, getSpotify, getMedium, getNpm, getGem } from 'hooks'
import { env } from 'scripts/variables'

export const Layout:React.FC = ({ children }) => {

  // if (!env.is('test')) {
  //   getTrello();
  //   setCount();
  //   setHero();
  //   getSpotify();
  //   getMedium();
  //   getNpm();
  //   getGem();
  // }

  // if (env.is('local')) {
  //   console.log("state: ", useSelector(state => state))
  // }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Paul Heading | Front End Dev | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      { children }
      <Marquee />
      <Desktop />
      <Email />
      <Footer />
    </div>
  )
}
