export enum actionType {
  get_npm = 'get_npm',
  get_npm_success = 'get_npm_success',
  get_npm_error = 'get_npm_error',
  get_gem = 'get_gem',
  get_gem_success = 'get_gem_success',
  get_gem_error = 'get_gem_error',
  get_treehouse = 'get_treehouse',
  get_treehouse_success = 'get_treehouse_success',
  get_treehouse_error = 'get_treehouse_error',
  get_trello = 'get_trello',
  get_trello_success = 'get_trello_success',
  get_trello_error = 'get_trello_error',
  set_hero = 'set_hero',
  set_hero_success = 'set_hero_success',
  set_hero_error = 'set_hero_error',
  set_count = 'set_count',
  set_count_success = 'set_count_success',
  set_count_error = 'set_count_error',
  get_spotify = 'get_spotify',
  get_spotify_success = 'get_spotify_success',
  get_spotify_error = 'get_spotify_error',
  get_medium = 'get_medium',
  get_medium_success = 'get_medium_success',
  get_medium_error = 'get_medium_error'
}